#!/bin/sh

blog_url="https://samedamci.me/blog/index.html"
blog_title="samedamci's blog"
link="https://samedamci.me/blog/rss.xml"
description="Blog with my thoughts about world."

init() {
printf "%s\n" \
"<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">
<!-- Deployed with bloag (https://git.samedamci.me/samedamci/bloag) -->
<channel>
<title>$blog_title</title>
<description>$description</description>
<lastBuildDate>$date</lastBuildDate>
</channel>
</rss>" >"$output"
}

post_title() {
  grep -m 1 "a href=\"#[0-9].*" /tmp/bloag_site.html | \
    sed "s/.*<\/p> //g; s/<.*//g"
}

post_body() {
  line="$(grep -in "^ *<\/div>" /tmp/bloag_site.html | awk 'NR==1 {print $1}')"
  line2="$(head -n "${line%?}" /tmp/bloag_site.html | grep -m 1 -in \
    "<div id=\".*\" class=\"project\"" | awk 'NR==1 {print $1}'
  )"
  head -n "${line%?}" /tmp/bloag_site.html > /tmp/bloag_site2.html
  sed "1,${line2%?}d" /tmp/bloag_site2.html | sed '1d; $ d' | \
    sed 's/\//\\\//g; s/\"/\\\"/g' | tr -d '\n' | sed 's/   //g; s/  / /g; s/^ //g;'
}

add_post() {
sed -i "s/<\/lastBuildDate>/<\/lastBuildDate>\n\
<item>\n\
<title>$(post_title)<\/title>\n\
<link>\\$post_link<\/link>\n\
<description><![CDATA[\n\
$(post_body)\n\
]]><\/description>\n\
<pubDate>$date<\/pubDate>\n\
<\/item>/g; s/<lastBuildDate>.*<\/lastBuildDate>/\
<lastBuildDate>$date<\/lastBuildDate>/g" "$output"
}

backup() {
  cp "$output" "$output.backup"
}

post_link="$link"

curl -s "$blog_url" > /tmp/bloag_site.html
date="$(date +"%a, %d %b %Y %H:%M:%S +0200")"

help_message="
Usage: bloag [-h] [-o FILE]

  -o FILE     Output file
"

while getopts 'o::h' c
do
  case $c in
    o) output="$OPTARG";;
    h) echo "$help_message"; exit 0;;
    [?]) echo "Invalid option, use '-h'."; exit 1;;
  esac
done

if [ ! -f "$output" ]; then init; else
  backup && add_post
fi

rm -f /tmp/bloag*
